lsd1_image_group_path: 'C:/Users/zbedd/OneDrive/GT/Opportunities/Katz Lab/LSD1 Mislocalization/LSD1 pTau Images 7/'
fiji_seq_table_rel_path: 'LSD1_pTau_7_fiji_6_16_2025.csv'

display_plots : False

save_artifacts: True
output_path: 'C:/Users/zbedd/OneDrive/GT/Opportunities/Katz Lab/LSD1 Mislocalization/LSD1 pTau Images 7/'

# Optional subset of groups to analyze, e.g. ['A', 'B']
groups: ['A', 'C', 'E', 'G', 'I', 'K']

# Optional list of group comparisons, e.g. [['A', 'B'], ['A', 'C']]
comparisons: 

# # With and w/o tau | M and N are excluded due to insufficient sample size
# comparisons: [['A', 'B'], ['C', 'D'], ['E', 'F'], ['G', 'H'], 
#               ['I', 'J'], ['K', 'L']]

